### ISSUE TITLE
Driver INF Location?

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC980_NuWriter#1]
When I plug an NUC980 into my computer using USB, no drivers are installed. I noticed you're using WinUSB, so I used Zadig to force-install a WinUSB driver. I modified NucWinUsb.h to use the new Interface GUID, but unfortunately, many other devices on my system use this Interface GUID, which causes the program to malfunction (since it relies on Interface GUIDs instead of VID/PID sniffing).

I assume there's a proper INF driver floating around that uses the correct Interface GUID? Where can I find this?

**Comment by yachen** [comment]
Hi,

Please download NUC980 BSP (Linux or Non-OS) from 
[https://www.nuvoton.com/hq/products/microprocessors/arm9-mpus/Software/?__locale=en&resourcePage=Y](url)

You can find the required driver WinUSB4NuVCOM.exe in tools/ directory. Thanks.


Sincerely,

Yi-An Chen

**Comment by jaydcarlson** [comment]
Thank you!


__________________________________
Jay Carlson
Graduate Research Assistant
Perceptual Systems Research Group
http://psrg.unl.edu
402-310-0340 (cellular)

________________________________
