### ISSUE TITLE
关于NuWriter v1.18 烧录 NUC980DK61Y Nor Flash Environment失败问题

### ISSUE THREAD

**Issue by QHxiedong** [OpenNuvoton/NUC980_NuWriter#10]
用NuWriter v1.18 烧录NUC980DK61Y Nor Flash（W25Q256）Environment，烧录正常，但是单板运行时会报错，bad CRC，emac地址没有设置。
现在我只能通过手动敲命令保存信息让单板运行下去。
setenv ipaddr 192.168.0.101
setenv ethaddr 00:0c:29:64:67:89
setenv bootcmd sf probe 0 30000000\; sf read 0x7fc0 0x200000 0x1e00000\; bootm 0x7fc0
saveenv

这里有我的env.txt文件，请问如何解决问题？谢谢！

![烧录截图](https://user-images.githubusercontent.com/84755077/158611069-6d459b4a-0ef4-44c4-ab45-e69c684380f9.jpg)
![运行截图](https://user-images.githubusercontent.com/84755077/158611080-1ceab5c1-e4de-459b-b94d-2440c2f340eb.jpg)
[env.txt](https://github.com/OpenNuvoton/NUC980_NuWriter/files/8262954/env.txt)

**Comment by QHxiedong** [comment]
能否帮忙看下我的问题，谢谢！

**Comment by ychuang3** [comment]
env.txt 的 Image Type 要選擇 Environment

**Comment by QHxiedong** [comment]
加载的env.txt文件时是选择的Environment，从截图可以看的到type选择的是ENV

![image](https://user-images.githubusercontent.com/84755077/167366904-2e79131a-3700-4908-b30a-ae0b1c171da9.png)

**Comment by cwweng-nuvoton** [comment]
env.txt 中，每行要用 WINDOWS 回車符號, 若用 UNIX 的回車符號會掉字

**Comment by QHxiedong** [comment]
我在windows环境下新建了env.txt，重新烧录还是报错误。
![image](https://user-images.githubusercontent.com/84755077/167615417-fbf30a49-ca49-43f7-9580-ce5f148c527f.png)
![image](https://user-images.githubusercontent.com/84755077/167615790-b3e4a740-8db4-438e-b9f7-12e8ae52afc1.png)

我新建的env.txt如下所示：
[env.txt](https://github.com/OpenNuvoton/NUC980_NuWriter/files/8661003/env.txt)

**Comment by cwweng-nuvoton** [comment]
我用你的 env.txt 燒錄是 OK 的
![image](https://user-images.githubusercontent.com/47778290/167652518-fd1f77e3-cce6-4a2e-88f6-039907ece9c7.png)

U-Boot 開機後,  透過 "env print" 可以看到你設定的環境變數
![image](https://user-images.githubusercontent.com/47778290/167652868-c75ea338-c26f-4ff8-a510-23ea28730ecd.png)

**Comment by cwweng-nuvoton** [comment]
附上我的 u-boot.bin
[u-boot.zip](https://github.com/OpenNuvoton/NUC980_NuWriter/files/8665737/u-boot.zip)

**Comment by QHxiedong** [comment]
我用你提供的u-boot可以了，非常感谢！
那么我的问题原因应该在u-boot这里。
对比了2份u-boot，不同的我用红色圈标记出来了。
问题1：U-Boot 2016.11-后面的信息是代表什么？ 
问题2：哪里定义W25Q256的erase size ？
谢谢！
![image](https://user-images.githubusercontent.com/84755077/167750654-ab709d1d-2ef5-4ae5-8112-fc3c337ec6a1.png)

**Comment by cwweng-nuvoton** [comment]
1. U-Boot 2016.11 後面的是 U-Boot 產生的版本號, 不用理他
2. W25Q256 的 erase size 定義在 drivers/mtd/spi/sf_params.c 當中的 spi_flash_params_table[]

**Comment by QHxiedong** [comment]
我在sf_params.c 中更改了 erase size，如下所示：
![image](https://user-images.githubusercontent.com/84755077/167763604-4b3a1b85-0995-42b5-b5c7-202c275bfc17.png)
但是还是会出现之前的问题，所以问题还不是erase size，如下所示我新编译的u-boot：
![image](https://user-images.githubusercontent.com/84755077/167763758-0a8b96bf-821b-48cf-a457-408b5d5c23ab.png)

我用的是nuc980_eth2uart_defconfig，然后在include/configs/nuc980_eth2uart.h修改为spi flash，如下所示：
![image](https://user-images.githubusercontent.com/84755077/167764524-860bfd0d-ffbc-40e1-afc8-a36ba18e7538.png)
下面是我的nuc980_eth2uart.h文件：
[nuc980_eth2uart.zip](https://github.com/OpenNuvoton/NUC980_NuWriter/files/8666555/nuc980_eth2uart.zip)

请帮忙看看问题可能在哪里，谢谢！

**Comment by cwweng-nuvoton** [comment]
你的 CONFIG_ENV_SIZE 和 CONFIG_ENV_SECT_SIZE 定義錯了, 應該是 0x10000 (64KB)
![image](https://user-images.githubusercontent.com/47778290/167766934-11634e0b-495c-444a-bcb3-79dd75527320.png)

附上我的 nuc980_evb.h,  雖然是不同板子,  但設定大同小異, 請參考一下
[nuc980_evb.zip](https://github.com/OpenNuvoton/NUC980_NuWriter/files/8666669/nuc980_evb.zip)

**Comment by QHxiedong** [comment]
是 CONFIG_ENV_SIZE 和 CONFIG_ENV_SECT_SIZE 定义错了的原因，我更改成0x10000就可以了，非常非常感谢你！
另外我也试验了falsh的erase size定义 4K和64K都是可以的，源码中erase size是64K的，你更改成4K有什么特殊原因吗？谢谢！

**Comment by cwweng-nuvoton** [comment]
Erase size 是在 drivers/mtd/spi/spi_flash.c 當中決定, 
如果有定義 CONFIG_SPI_FLASH_USE_4K, 會根據 該 SPI Flash 在spi_flash_params_table[] 當中是否有 SECT_4K 這個屬性, 如果有, Erase size 就是 4K, 沒有的話, 就是 64 K 
如果沒有定義 CONFIG_SPI_FLASH_USE_4K, 就一律是 64 K
![image](https://user-images.githubusercontent.com/47778290/167778939-422c7984-79c4-45d6-a275-9a323cd2e789.png)

可能之前在 menuconfig 中無意勾選了 CONFIG_SPI_FLASH_USE_4K, 沒有特殊原因.

**Comment by QHxiedong** [comment]
感谢你的详细解答，谢谢！
