### ISSUE TITLE
使用spi nand+双网口时，nuwrite连接卡死

### ISSUE THREAD

**Issue by 1020165558** [OpenNuvoton/NUC980_NuWriter#2]
使用spi nand+双网口时，USB启动，nuwrite连接卡死在emmc1检测。请问如何关掉IBR中的emmc1检测。
以下为打印信息
DDR-OK
=======================================
Run firmware code
CPU: 300MHz, DDR: 300MHz, SYS: 300MHz, PCLK: 150MHz
Parse NuWriter command line
=======================================
SPI NOR ID=0x0000ffff  _spi_type =0
SPI NOR ID=0x0000ffff  _spi_type =0

SPI NAND: Auto Detect
ID=[0xefaa21]
BlockPerFlash = 1024, PagePerBlock = 64
PageSize = 2048, SpareArea = 64
QuadReadCmd    = 0x6b
ReadStatusCmd  = 0xff
WriteStatusCmd = 0xff
StatusValue    = 0xff
Dummybyte      = 0x1

NAND ID=[17][17][17][17]
PowerOn setting 0x5f6000d4
BlockPerFlash=-7, PagePerBlock=64, PageSize=2048

eMMC1/SD1

**Comment by yachen** [comment]
請問是冊是最新版本嗎? 3f0910f8 有在 SD/eMMC 檢測中加了 timeout.

**Comment by 1020165558** [comment]
谢谢，下载最新版本可以了
