### ISSUE TITLE
 NUC980_NuWriter 烧写报错Err-DDR

### ISSUE THREAD

**Issue by wall-xv** [OpenNuvoton/NUC980_NuWriter#6]
NUC980_NuWriter 烧写报错
NUC980 IBR 20180813
Boot from USB
Err-DDR
不能完成烧写。
有没有解决办法，还是芯片坏了？

**Comment by yachen** [comment]
Hi, 是什麼板子上測試的? 請確認選擇的 ini 跟板子上的 IC 型號有匹配.

**Comment by wall-xv** [comment]
是自己生产的板子，用NUC980DK61YC，一个批次约有5%出现。



许华雄
深圳玖加科技有限公司
13723708202


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenNuvoton/NUC980_NuWriter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenNuvoton/NUC980_NuWriter]  NUC980_NuWriter 烧写报错Err-DDR (#6)





 
Hi, 是什麼板子上測試的? 請確認選擇的 ini 跟板子上的 IC 型號有匹配.

**Comment by yachen** [comment]
若是確認ini 的型號有選對, 請檢查 DDR 相關的電源是否有 noise. 一批出現 5% 比較可能是硬件問題.

**Comment by wall-xv** [comment]
刚试了选DK41可以烧写，丝印确实是DK61，这样也可以使用。
非常感谢！

**Comment by blockchain4trust** [comment]
谢谢您的建议，上面提到的 NUC980 出现 Err-DDR 的错误，是由硬件电源时序引起的。

故障版本的 PCB 使用了电源芯片 EA3036 它 pmu 的 1.2V/1.8V/3.3V 这 3 种电源时序，
不能吻合 NUC980 的上电时序，导致启动失败。

上电时序请参考《NUC980 Hardware Development Guide_V1.0》
https://www.nuvoton.com.cn/resource-download.jsp?tp_GUID=DA00-NUC980-1&currentFolder=/products/microprocessors/arm9-mpus/nuc980-industrial-control-iot-series/

现在按 nuvoton 官方推荐的 DC-DC 设计电源，在小批 30 片 PCB 没有出现 Err-DDR 错误。

DC-DC 电源设计，请参考《HW_NK-980IoT_V1.0》 https://www.nuvoton.com.cn/resource-download.jsp?tp_GUID=UG1020190308162722&currentFolder=/products/microprocessors/arm9-mpus/nuc980-industrial-control-iot-series/
