### ISSUE TITLE
SPI NAND: Error MXIC spiNAND_ReadyBusy_Check timeout

### ISSUE THREAD

**Issue by flownder** [OpenNuvoton/NUC980_NuWriter#7]
Hi,
i'm try to load image to NK-NUC98R board
But spi-nand not response

![image](https://user-images.githubusercontent.com/71446776/125934019-bef5be2e-e7c9-4122-9eef-8e0f7fbc4898.PNG)

**Comment by yachen** [comment]
Hi, What's the part number of this SPI NAND?

**Comment by flownder** [comment]
![IMG_4816](https://user-images.githubusercontent.com/71446776/125955344-ff5cf1f3-8a9e-4832-be31-32974cd57fd7.jpg)

**Comment by yachen** [comment]
Hi, That's a NAND flash, not SPI NAND flash.

**Comment by flownder** [comment]
Oops,
![Uploading 597F07FE-D6C7-48E9-A1DD-1E63C5128DBB.jpeg…]()

**Comment by flownder** [comment]
![A45FC644-79DD-4FE5-BB82-3DDED2752FEE](https://user-images.githubusercontent.com/71446776/125976105-93145f1f-743c-4f0a-8298-d0b011b11e5c.jpeg)

**Comment by flownder** [comment]
25X10BVNIG

**Comment by yachen** [comment]
Hi, This is a SPI NOR flash, not a SPI NAND flash.  Probable there's no SPI NAND on your board?

**Comment by flownder** [comment]
yes, i don't see spi-nand chip on board. How to disable warning message? Disable spi-nand support in uboot and kernel?
